version: "3.9"

services:
  db:
    container_name: postgresdb
    image: postgres
    restart: always
    shm_size: 128mb
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123!

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - "8000"
    ports:
      - "8000:8000"
    # volumes:
    #   - ./backend:/app
    depends_on:
      - db

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    expose:
      - "3000"
    ports:
      - "3000:3000"
    # volumes:
    #   - ./frontend:/app
